# Generated by Django 4.2.17 on 2025-02-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('fdate', models.DateField()),
                ('ffare', models.FloatField()),
                ('fstart', models.CharField(max_length=25)),
                ('fend', models.CharField(max_length=25)),
            ],
        ),
    ]
